CREATE TABLE software_system
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID                                    NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_software_system PRIMARY KEY (id)
);

ALTER TABLE software_system
    ADD CONSTRAINT uc_software_system_uuid UNIQUE (uuid);
